### ISSUE TITLE
website

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/RforMassSpectrometry.org#1]
@sgibb @jorainer - I am preparing a simple landing page for the website. 

I would need your input (either in this or other issue, or on slack). Let me know if there are any specific points that you would like to be mentioned and whether you are happy with what I have so far (more to come).

**Comment by jorainer** [comment]
Would would be nice is to point out current and future developments. Just to let people know what we're currently working on.

Also, we should have a *projects* repository or similar where we could collect project ideas (for future developments). This might also be useful if interested students want to pick a software development project or similar.
This could be one folder for one project, with a readme.md in it (and optionally additional files) describing project ideas and discussing things. That's at the moment how I try to manage all the data analysis projects I am supposed to process.

**Comment by lgatto** [comment]
> Would would be nice is to point out current and future developments.

Yes, but I'm not sure this would be the best place to describe the developments, as opposed to the individual package repositories. Here, we could have an general overview of the initiative, and redirect to the individual packages.

> Also, we should have a projects repository ...

A place to collect input or idea would be useful. But I think this needs to be formalised somehow, so we would need to curate this file based on community input. This could also come in individual package repos.

What I would like to do, however, is something along the lines of the [tidyverse](https://www.tidyverse.org/) website, the *RforMassSpectrometry* being the main landing page, and links all the packages under the organisation, all with a common there using *~pkgdown~* *blogdown*.

**Comment by sgibb** [comment]
I think RforMassSpectrometry.org should focus on the users. So a landing page in the style of the tidyverse one would be great. We could provide a development roadmap (which is IMHO hard to realize) in a special github repository/wiki. I guess most advanced users or developers are used to github.

**Comment by lgatto** [comment]
Hi @sgibb and @jorainer. I have a first draft of the site produced with `blogdown`  up and running at http://www.rformassspectrometry.org/. We need
- a different image for the home page 
- ideas/comments for content

**Comment by jorainer** [comment]
For the roadmap, I think we have to somehow organize our development efforts, i.e. define what has to be done and who is doing it. We can do this within each package, sure, but in the end the packages have to work smoothly together. So, having some global view what is done and what is missing would not hurt. We can discuss that in the next dev call.

For the landing page: very nice. Content is fine I think. For the image, we could use stickers for the packages - once we have them...

**Comment by lgatto** [comment]
I thought about using the package stickers on the Packages page. But we could also arrange them in a nice way on the home page.

**Comment by lgatto** [comment]
@rformassspectrometry/core I think we can use the `RforMassSpectrometry` package to present (in vignettes) and discuss (in issues) the roadmap of the initiative.
