### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/RforMassSpectrometry.org#2]
What communication channels should we offer. I could think of a Google group (although that requires a Google account, and they aren't that nice), a plain mailing list (I might be able to create one at my university), github issues (requires a github account),... or simply a shared/group email address that we all get emails forwarded from? 

Any ideas @sgibb @jorainer

**Comment by jorainer** [comment]
I think github issues will be the most important channel for us, because we're aiming mostly at developers I guess.

Other possibilities:
- slack (seems to be quite popular nowadays)
- twitter ?

**Comment by lgatto** [comment]
I don't really want to maintain a dedicated twitter account - let's rather use the `#RforMassSpec` hastag.

Slack is probably an option, although it also requires a dedicated account. We could do that plus a general *contact* form that sends us an email.

**Comment by lgatto** [comment]
May be we could have a simple contact form for general contact, a slack channel, and then use the respective issues for stuff that needs to be tracked or is related to a project or package development?

**Comment by sgibb** [comment]
I would favour a mailing list/e-mail alias. I am not a fan of slack/twitter.

**Comment by jorainer** [comment]
I'm fine with anything.

**Comment by lgatto** [comment]
I have settled for now for a simple contact page with information as to how to get in touch or ask questions depending on the topic. I have also added my general group email as contact for now. This could be changed to an `@RforMassSpectrometry.org` email.
