### ISSUE TITLE
An RforMassSpectrometry package

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/RforMassSpectrometry.org#4]
On the [Packages](https://www.rformassspectrometry.org/pkgs/) page, I wrote the following

> Execute `BiocManager::install("RforMassSpectromety")` to install all the RforMassSpectrometry packages.

which begs the question:

- Should we create an `RforMassSpectrometry` meta-package (like `tidyverse`) that install some core packages, and possibly offers some other, general functionality? 

@sgibb @jorainer

**Comment by jorainer** [comment]
Yes, that would make sense.

**Comment by lgatto** [comment]
I think so too, especially in the light of `RforMassSpectrometry`. On the other hand, I don't want to overkill things. 

Curious as to what @sgibb thinks.

**Comment by lgatto** [comment]
See https://github.com/rformassspectrometry/RforMassSpectrometry and [this comment](https://github.com/rformassspectrometry/RforMassSpectrometry.org/issues/1#issuecomment-499637554).
